### ISSUE TITLE
Fix missing translation warnings (in resource XML)

### ISSUE THREAD

**Issue by grauwoelfchen** [zdavatz/generika_android#16]
I still get the following warning 
`> Task :app:lintVitalRelease 
/home/zeno/.software/generika_android/app/src/main/res/values/arrays.xml:10: Error: "settings_search_type_values" is not translated in "de" (German), "fr" (French) [MissingTranslation]
  <string-array name="settings_search_type_values">
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/zeno/.software/generika_android/app/src/main/res/values/arrays.xml:24: Error: "settings_search_lang_values" is not translated in "de" (German), "fr" (French) [MissingTranslation]
  <string-array name="settings_search_lang_values">
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/zeno/.software/generika_android/app/src/main/res/values/arrays.xml:37: Error: "settings_app_locale_values" is not translated in "de" (German), "fr" (French) [MissingTranslation]
  <string-array name="settings_app_locale_values">
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/zeno/.software/generika_android/app/src/main/res/values/strings.xml:75: Error: "lang_en_name" is not translated in "fr" (French) [MissingTranslation]
    <string name="lang_en_name">English</string>
            ~~~~~~~~~~~~~~~~~~~
/home/zeno/.software/generika_android/app/src/main/res/values/strings.xml:79: Error: "lang_en_abbr" is not translated in "fr" (French) [MissingTranslation]
    <string name="lang_en_abbr">en</string>
            ~~~~~~~~~~~~~~~~~~~
`
for 
`
make release
`

**Comment by zdavatz** [comment]
Lets also fix these remaining translations warning.

**Comment by zdavatz** [comment]
`make clean` worked, thank you.
