### ISSUE TITLE
Use Default Android Download Manager to open a downloaded AMK File.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/generika_android#39]
* https://stackoverflow.com/questions/7239996/android-downloadmanager-api-opening-file-after-download/7240108
* https://developer.android.com/reference/android/app/DownloadManager.html
* https://developer.android.com/reference/android/app/DownloadManager.html#COLUMN_MEDIA_TYPE

**Comment by grauwoelfchen** [comment]
Download Manager API is not related to this `Opening` Problem in some Apps.
So, see issue #40.

**Comment by zdavatz** [comment]
How can we open .amk Files via the Download Manager then?
