### ISSUE TITLE
Show errors using alert dialog at prescription import

### ISSUE THREAD

**Issue by grauwoelfchen** [zdavatz/generika_android#42]
Check the Hash is the prescription has already been imported or not. Notify the user according to how it is done on Generika App for iPhone.
See. https://github.com/zdavatz/generikacc/search?utf8=%E2%9C%93&q=Success&type=

**Comment by grauwoelfchen** [comment]
Above commit introduces following new translation texts on alert dialog for prescription import:

### English `en`
- https://github.com/zdavatz/generika_android/blob/master/app/src/main/res/values/strings.xml#L106-L112

### Deutsch `de`
- https://github.com/zdavatz/generika_android/blob/master/app/src/main/res/values/strings.xml#L106-L112

### Français `fr`
- https://github.com/zdavatz/generika_android/blob/master/app/src/main/res/values-fr/strings.xml#L91-L97

**Comment by zdavatz** [comment]
DE and EN are the same Line numbers. Will check now.
