### ISSUE TITLE
Put the package name under the expiry date dialog

### ISSUE THREAD

**Issue by grauwoelfchen** [zdavatz/generika_android#56]
Because the dialog for expiry date input of scanned drugs is a little bit large. It hides almost all of the background (list of the drugs). User (me) can forget the selected package, easily. So, It might be good to put the package name (or, and also size) of selected drug under the title of the dialog.

![verfalldatum-month-year-picker-dialog-20180412](https://user-images.githubusercontent.com/163063/38652414-cf299d42-3e40-11e8-8e3e-5b07a8aaeff5.jpg)

**Comment by zdavatz** [comment]
This is not necessary. We first need to implement the 2D Matrix Code Scanner. In the future, the Expiry date will anyway be set via  the 2D Matrix-Code.
See: https://www.gs1.org/docs/barcodes/GS1_DataMatrix_Guideline.pdf
page 19 and page 20

**Comment by grauwoelfchen** [comment]
OK.
