### ISSUE TITLE
Scanning Test-Image by Philip

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/generika_android#59]
Can we scan this with Generika-Android App?

![datamatrix](https://user-images.githubusercontent.com/4953/38923377-acdbf640-42fa-11e8-97b3-c07a86b41a15.jpeg)

**Comment by grauwoelfchen** [comment]
![github-issue-59-barcode-detection--works-20180419](https://user-images.githubusercontent.com/163063/38968729-b1d04a3e-43c7-11e8-850b-f185c8deae01.jpg)

(The first row on list view behind the alert dialog is detected record)
