### ISSUE TITLE
Scanning unclear 2D Matrix Code cause App to crash

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/generika_android#71]
Scanning this code causes the App to crash:

![img_1773](https://user-images.githubusercontent.com/4953/39270738-39ccdd26-48d7-11e8-92a6-18ab6b8a59e8.PNG)

Crashlog should be in the Google-Store-Play console.

**Comment by zdavatz** [comment]
Stacktrace ist hier: https://play.google.com/apps/publish/?account=4921779936452011385#ErrorClusterDetailsPlace:p=org.oddb.generika&et=CRASH&sh=false&lr=LAST_7_DAYS&av=1.0.49&ecn=java.lang.NullPointerException&tf=Product.java&tc=org.oddb.generika.model.Product$Barcode&tm=%253Cinit%253E&nid&an&c&s=new_status_desc&ed=1524688028857

**Comment by grauwoelfchen** [comment]
NOTE:

Now, this result of scanning this barcode image will look like:
![unclear-image-barcode-20180426](https://user-images.githubusercontent.com/163063/39290636-4197592a-496b-11e8-932a-22ac9a012bee.jpg)
